export interface DonorRegistrationRequest {
  firstName: string;
  middleName?: string;
  lastName: string;
  addressLine1: string;
  addressLine2?: string;
  city: string;
  province: string;
  zipCode: string;
  email: string;
  mobileNumber: string;
  sex: string;
  bloodType: string;
}

export interface DonorRegistrationResponse {
  // Indicates whether the donor registration was successful. If true, the registration was successful; if false, there was an error during the registration process.
  success: boolean;

  // Optional error message providing details about the error that occurred during the donor registration process. This field is present only if 'success' is false.
  error?: string;

  // Optional donor object containing the details of the registered donor. This field is present only if 'success' is true and the donor was successfully registered.
  donor?: {
    // Unique identifier for the donor, represented as a string. This field is generated by the database upon successful registration of the donor.
    id: string;

    // Timestamp indicating when the donor record was created, represented as a string in ISO 8601 format. This field is generated by the database upon successful registration of the donor.
    created_at: string | null;

    // Donor's personal information fields, including first name, middle name (optional), last name, email, mobile number, street
    first_name: string;
    middle_name: string | null;
    last_name: string;

    // Donor's contact information fields, including email and mobile number. Both fields are required and cannot be null.
    email: string;
    mobile_no: string;

    // Donor's address information fields, including street address and zip code. Both fields are required and cannot be null.
    street: string;
    zip_code: string;

    // Donor's personal attributes,
    sex: string;
    blood: string;

    // Foreign key relationship to the 'city' table, which links the donor to a specific city. The 'references' method establishes the relationship, and the 'onDelete' and 'onUpdate' options specify that no action should be taken on the donor record if the referenced city is deleted or updated.
    city_id: string;

    // Donor's photo path, which is a required field that stores the file path to the donor's photo. This field cannot be null.
    photo_path: string;

    // Donor's physical attributes, including height and weight. Both fields are optional and can be null.
    height: number | null;
    weight: number | null;
    active: boolean;
  };
}